import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MICAPA - Ministerio El Camino de la Palabra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <nav>
          <ul className="text-white">
            <Link href="/">
              <li className="text-white">Inicio</li>
            </Link>
            <Link href="/contacto">
              <li className="text-white">Contacto</li>
            </Link>
            <Link href="/blog">
              <li className="text-white">Blog</li>
            </Link>
            <Link href="/radio">
              <li className="text-white">Radio</li>
            </Link>
            <Link href="/nosotros">
              <li className="text-white">Nosotros</li>
            </Link>
            <Link href="/devocionales">
              <li className="text-white">Devocionales</li>
            </Link>
            <Link href="/oraciones">
              <li className="text-white">Oración</li>
            </Link>
            <Link href="/estudio">
              <li className="text-white">Enseñanza</li>
            </Link>
            <Link href="/jovenes">
              <li className="text-white">Youth</li>
            </Link>
            <Link href="/niños">
              <li className="text-white">Caleb</li>
            </Link>
            <Link href="/recursos">
              <li className="text-white">Media</li>
            </Link>
            <Link href="/app-micapa">
              <li className="text-white">App</li>
            </Link>
            <Link href="/">
              <li className="text-white">Social</li>
            </Link>
            <Link href="/soporte">
              <li className="text-white">Soporte</li>
            </Link>
            <Link href="/eventos">
              <li className="text-white">Eventos</li>
            </Link>
            <Link href="/politica-de-cookies">
              <li className="text-white">Políticas de Cookies</li>
            </Link>
            <Link href="/seguridad-y-privacidad">
              <li className="text-white">Políticas de Privacidad y seguridad</li>
            </Link>
            <Link href="/aviso-legal">
              <li className="text-white">Aviso Legal</li>
            </Link>
          </ul>
        </nav>
      </header>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
